-- MySQL Schema for EduConecta
-- Run: mysql -u root -p < schema.sql

CREATE DATABASE IF NOT EXISTS educonecta CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE educonecta;

-- Institution
CREATE TABLE Institution (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL UNIQUE,
  type VARCHAR(50) DEFAULT 'public' COMMENT 'public, private',
  ruc VARCHAR(11) DEFAULT NULL,
  address VARCHAR(255),
  district VARCHAR(255),
  province VARCHAR(255),
  department VARCHAR(255),
  phone VARCHAR(255),
  email VARCHAR(255),
  website VARCHAR(255),
  directorName VARCHAR(255),
  educationalLevel VARCHAR(255) COMMENT 'inicial, primaria, secundaria (comma separated)',
  shifts VARCHAR(255) COMMENT 'morning, afternoon, evening (comma separated)',
  foundedYear INT DEFAULT NULL,
  description TEXT,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- User
CREATE TABLE User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL COMMENT 'SUPER_ADMIN, INSTITUTIONAL_ADMIN, TEACHER, PARENT',
  phone VARCHAR(255),
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  institutionId INT,
  FOREIGN KEY (institutionId) REFERENCES Institution(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- InstitutionalAdmin
CREATE TABLE InstitutionalAdmin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL UNIQUE,
  institutionId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (institutionId) REFERENCES Institution(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Teacher
CREATE TABLE Teacher (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL UNIQUE,
  institutionId INT NOT NULL,
  speciality VARCHAR(255),
  assignedLevels JSON DEFAULT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (institutionId) REFERENCES Institution(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Parent
CREATE TABLE Parent (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL UNIQUE,
  institutionId INT NOT NULL,
  occupation VARCHAR(255),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (institutionId) REFERENCES Institution(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Grade
CREATE TABLE Grade (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  level VARCHAR(255),
  institutionId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (institutionId) REFERENCES Institution(id) ON DELETE CASCADE,
  UNIQUE KEY uk_grade_name_level (name, level, institutionId)
) ENGINE=InnoDB;

-- Section
CREATE TABLE Section (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  gradeId INT NOT NULL,
  capacity INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (gradeId) REFERENCES Grade(id) ON DELETE CASCADE,
  UNIQUE KEY uk_section_name_grade (name, gradeId)
) ENGINE=InnoDB;

-- Student
CREATE TABLE Student (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  documentId VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(255),
  institutionId INT NOT NULL,
  gradeId INT,
  sectionId INT,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (institutionId) REFERENCES Institution(id) ON DELETE CASCADE,
  FOREIGN KEY (gradeId) REFERENCES Grade(id) ON DELETE SET NULL,
  FOREIGN KEY (sectionId) REFERENCES Section(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ParentStudent (many-to-many)
CREATE TABLE ParentStudent (
  parentId INT NOT NULL,
  studentId INT NOT NULL,
  relationship VARCHAR(255),
  PRIMARY KEY (parentId, studentId),
  FOREIGN KEY (parentId) REFERENCES Parent(id) ON DELETE CASCADE,
  FOREIGN KEY (studentId) REFERENCES Student(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Course
CREATE TABLE Course (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(255),
  description VARCHAR(255),
  institutionId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (institutionId) REFERENCES Institution(id) ON DELETE CASCADE,
  UNIQUE KEY uk_course_name_institution (name, institutionId)
) ENGINE=InnoDB;

-- CourseTeacher
CREATE TABLE CourseTeacher (
  id INT AUTO_INCREMENT PRIMARY KEY,
  courseId INT NOT NULL,
  teacherId INT NOT NULL,
  gradeId INT,
  sectionId INT,
  FOREIGN KEY (courseId) REFERENCES Course(id) ON DELETE CASCADE,
  FOREIGN KEY (teacherId) REFERENCES Teacher(id) ON DELETE CASCADE,
  FOREIGN KEY (gradeId) REFERENCES Grade(id) ON DELETE SET NULL,
  FOREIGN KEY (sectionId) REFERENCES Section(id) ON DELETE SET NULL,
  UNIQUE KEY uk_course_teacher_grade_section (courseId, teacherId, gradeId, sectionId)
) ENGINE=InnoDB;

-- Schedule
CREATE TABLE Schedule (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dayOfWeek INT NOT NULL,
  startTime VARCHAR(255) NOT NULL,
  endTime VARCHAR(255) NOT NULL,
  classroom VARCHAR(255),
  shift VARCHAR(255) NOT NULL DEFAULT 'MAÑANA',
  courseId INT NOT NULL,
  institutionId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (courseId) REFERENCES Course(id) ON DELETE CASCADE,
  FOREIGN KEY (institutionId) REFERENCES Institution(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Enrollment
CREATE TABLE Enrollment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  studentId INT NOT NULL,
  gradeId INT NOT NULL,
  sectionId INT NOT NULL,
  academicYear VARCHAR(255) NOT NULL,
  enrollmentDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (studentId) REFERENCES Student(id) ON DELETE CASCADE,
  FOREIGN KEY (gradeId) REFERENCES Grade(id) ON DELETE CASCADE,
  FOREIGN KEY (sectionId) REFERENCES Section(id) ON DELETE CASCADE,
  UNIQUE KEY uk_student_academic_year (studentId, academicYear)
) ENGINE=InnoDB;

-- Attendance
CREATE TABLE Attendance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  studentId INT NOT NULL,
  teacherId INT NOT NULL,
  date DATETIME NOT NULL,
  isPresent TINYINT(1) NOT NULL DEFAULT 1,
  note VARCHAR(255),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (studentId) REFERENCES Student(id) ON DELETE CASCADE,
  FOREIGN KEY (teacherId) REFERENCES Teacher(id) ON DELETE CASCADE,
  UNIQUE KEY uk_student_date (studentId, date)
) ENGINE=InnoDB;

-- Tardiness
CREATE TABLE Tardiness (
  id INT AUTO_INCREMENT PRIMARY KEY,
  studentId INT NOT NULL,
  teacherId INT NOT NULL,
  date DATETIME NOT NULL,
  minutesLate INT NOT NULL,
  note VARCHAR(255),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (studentId) REFERENCES Student(id) ON DELETE CASCADE,
  FOREIGN KEY (teacherId) REFERENCES Teacher(id) ON DELETE CASCADE,
  UNIQUE KEY uk_tardiness_student_date (studentId, date)
) ENGINE=InnoDB;

-- Homework
CREATE TABLE Homework (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  dueDate DATETIME NOT NULL,
  courseId INT NOT NULL,
  teacherId INT NOT NULL,
  gradeId INT,
  sectionId INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (courseId) REFERENCES Course(id) ON DELETE CASCADE,
  FOREIGN KEY (teacherId) REFERENCES Teacher(id) ON DELETE CASCADE,
  FOREIGN KEY (gradeId) REFERENCES Grade(id) ON DELETE SET NULL,
  FOREIGN KEY (sectionId) REFERENCES Section(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- HomeworkSubmission
CREATE TABLE HomeworkSubmission (
  id INT AUTO_INCREMENT PRIMARY KEY,
  homeworkId INT NOT NULL,
  studentId INT NOT NULL,
  submitted TINYINT(1) NOT NULL DEFAULT 0,
  note VARCHAR(255),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (homeworkId) REFERENCES Homework(id) ON DELETE CASCADE,
  FOREIGN KEY (studentId) REFERENCES Student(id) ON DELETE CASCADE,
  UNIQUE KEY uk_homework_student (homeworkId, studentId)
) ENGINE=InnoDB;

-- GradeRecord
CREATE TABLE GradeRecord (
  id INT AUTO_INCREMENT PRIMARY KEY,
  studentId INT NOT NULL,
  courseId INT NOT NULL,
  teacherId INT NOT NULL,
  grade DECIMAL(5,2) NOT NULL,
  evaluationName VARCHAR(255) NOT NULL,
  evaluationDate DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (studentId) REFERENCES Student(id) ON DELETE CASCADE,
  FOREIGN KEY (courseId) REFERENCES Course(id) ON DELETE CASCADE,
  FOREIGN KEY (teacherId) REFERENCES Teacher(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Discipline
CREATE TABLE Discipline (
  id INT AUTO_INCREMENT PRIMARY KEY,
  studentId INT NOT NULL,
  teacherId INT NOT NULL,
  date DATETIME NOT NULL,
  description VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  isResolved TINYINT(1) NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (studentId) REFERENCES Student(id) ON DELETE CASCADE,
  FOREIGN KEY (teacherId) REFERENCES Teacher(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Communication
CREATE TABLE Communication (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  authorId INT NOT NULL,
  teacherId INT,
  institutionId INT NOT NULL,
  priority VARCHAR(255) NOT NULL DEFAULT 'normal',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (authorId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (teacherId) REFERENCES Teacher(id) ON DELETE SET NULL,
  FOREIGN KEY (institutionId) REFERENCES Institution(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Notification
CREATE TABLE Notification (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  message VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  userId INT NOT NULL,
  parentId INT,
  studentId INT,
  isRead TINYINT(1) NOT NULL DEFAULT 0,
  readAt DATETIME,
  confirmedAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (parentId) REFERENCES Parent(id) ON DELETE SET NULL,
  FOREIGN KEY (studentId) REFERENCES Student(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- NotificationRead
CREATE TABLE NotificationRead (
  id INT AUTO_INCREMENT PRIMARY KEY,
  notificationId INT NOT NULL,
  userId INT NOT NULL,
  readAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (notificationId) REFERENCES Notification(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  UNIQUE KEY uk_notification_user (notificationId, userId)
) ENGINE=InnoDB;

-- AuditLog
CREATE TABLE AuditLog (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  action VARCHAR(255) NOT NULL,
  entity VARCHAR(255) NOT NULL,
  entityId INT,
  details VARCHAR(255),
  ipAddress VARCHAR(255),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB;
