import * as Icons from "lucide-react"
import type { LucideProps } from "lucide-react"

const iconMap: Record<string, keyof typeof Icons> = {
  home: "Home",
  assignment: "ClipboardList",
  grade: "Star",
  mail: "Mail",
  dashboard: "LayoutDashboard",
  menu_book: "BookOpen",
  fact_check: "ClipboardCheck",
  person: "User",
  account_balance: "Landmark",
  groups: "Users",
  card_membership: "CreditCard",
  history: "History",
  calendar_month: "Calendar",
  qr_code_scanner: "QrCode",
  gavel: "Gavel",
  chat: "MessageCircle",
  group: "Users",
  school: "GraduationCap",
  diversity_3: "UserPlus",
  book: "Book",
  notifications: "Bell",
  how_to_reg: "UserPlus",
  file_upload: "Upload",
  payments: "Banknote",
  door_open: "DoorOpen",
  building: "Building2",
  users: "Users",
  credit_card: "CreditCard",
  settings: "Settings",
  bolt: "Zap",
  inbox: "Inbox",
  spark: "Sparkles",
  search: "Search",
  bell: "Bell",
  calendar: "Calendar",
  rocket: "Rocket",
  plus: "Plus",
  arrow_right: "ArrowRight",
  arrow_up_right: "ArrowUpRight",
  check: "Check",
  x: "X",
  graduationCap: "GraduationCap",
  edit: "Pencil",
  trash: "Trash2",
  eye: "Eye",
  refresh: "RefreshCw",
  filter: "SlidersHorizontal",
  download: "Download",
  external: "ExternalLink",
  layers: "Layers",
  trending: "TrendingUp",
  trending_down: "TrendingDown",
  wallet: "Wallet",
  shield: "ShieldCheck",
  lock: "Lock",
  globe: "Globe",
  pin: "Pin",
  pin_filled: "Pin",
  star: "Star",
  zap: "Zap",
  percent: "Percent",
  package: "Package",
  message: "MessageSquare",
  more: "MoreHorizontal",
  list: "List",
  grid: "LayoutGrid",
  layout: "LayoutDashboard",
  crown: "Crown",
  flask: "FlaskConical",
  palette: "Palette",
  tag: "Tag",
  clock: "Clock",
  chart: "BarChart3",
  chart_line: "LineChart",
  chart_pie: "PieChart",
  pulse: "Activity",
  database: "Database",
  cloud: "Cloud",
  server: "Server",
  devices: "Smartphone",
  map: "MapPin",
  power: "Power",
  lifebuoy: "LifeBuoy",
  arrow_left: "ArrowLeft",
}

export function getIcon(
  name: string,
  props?: LucideProps
): React.ReactElement | null {
  const key = iconMap[name]
  if (!key) return null
  const Cmp = Icons[key] as React.ComponentType<LucideProps>
  return <Cmp {...props} />
}