ALTER TABLE Schedule
  ADD COLUMN teacherId INT DEFAULT NULL AFTER courseId,
  ADD COLUMN gradeId INT DEFAULT NULL AFTER teacherId,
  ADD COLUMN sectionId INT DEFAULT NULL AFTER gradeId;

ALTER TABLE Schedule
  ADD FOREIGN KEY (teacherId) REFERENCES Teacher(id) ON DELETE SET NULL,
  ADD FOREIGN KEY (gradeId) REFERENCES Grade(id) ON DELETE SET NULL,
  ADD FOREIGN KEY (sectionId) REFERENCES Section(id) ON DELETE SET NULL;
